version: '3'

services:
  app:
    container_name: runroom-test-app
    image: runroom-test-app
    build:
      context: .
      dockerfile: .docker/app.dockerfile
    volumes:
      - .:/var/www:rw,cached
    networks:
      - app-tier
    working_dir: /var/www

networks:
  app-tier:
    driver: bridge
